# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v3
      #- run: docker build -t test_img .
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push to Docker Push
        env:
          REPO: photo-app-be
        run: |
          docker build -t $REPO .
          docker tag $REPO:latest ${{ secrets.DOCKER_USERNAME }}/$REPO:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/$REPO